### ISSUE TITLE
Resize of the window doesn't resize the graph

### ISSUE THREAD

**Issue by panuhorsmalahti** [ngyewch/angular-rickshaw#12]
The rickshaw element is only being resized when the data updates. The directive could watch for the resize event by e.g.
```
angular.element($window).on("resize", () => {
    // graph.render() and so on
});
```

This is also rather difficult to force from outside.

Here's a rickshaw resize example:
http://code.shutterstock.com/rickshaw/examples/resize

**Comment by ngyewch** [comment]
I've release a new version which resizes the graph to the size of its container on window resize.

**Comment by panuhorsmalahti** [comment]
Thanks! :+1:
