### ISSUE TITLE
Multiple axis elements

### ISSUE THREAD

**Issue by panuhorsmalahti** [ngyewch/angular-rickshaw#16]
When I e.g. resize the window (with the latest version), new elements are created for the y axis. These elements not only make the graph laggy, but the text becomes bold because the svg elements are overlapping.

The cause could be that every resize calls the update function, which re-renders the xAxis and the yAxis if they're configured.

**Comment by ngyewch** [comment]
This should be fixed in 0.8.2.

**Comment by panuhorsmalahti** [comment]
Thank you :+1:, I verified that this fix resolves the issue.
