### ISSUE TITLE
Custom X Axis Labels

### ISSUE THREAD

**Issue by patrickdmccarthy** [ngyewch/angular-rickshaw#9]
Hi,

The only option I've seen for x-axis formatting is the timeUnit property, but the problem is that my data is numbered 0-23 representing the hour, and rickshaw parses this as seconds rather than hours, so that if I use timeUnit = 'hour', it stays at 0 for the entire width of the graph.  Is there a way to implement custom x-axis labels with this directive?

**Comment by srlmproductions** [comment]
I haven't tried with the Angular part yet, but the second timebase for Rickshaw annoys me. I use milliseconds, so I made a new time fixture for that. You could do something similar.

https://github.com/srlmproductions/rickshaw/commit/dce8ac0e450045c74ad9e3d3f16379a89a74bcee

**Comment by ngyewch** [comment]
Hi Patrick,

The directive can only do what Rickshaw can do. Unfortunately, Rickshaw interprets x as seconds for a time axis. A simple work-around is to convert your x values (hours) to seconds. The alternative is what srlmproductions suggests, but the directive currently does not recognize custom fixtures.
